language: java
jdk:
  - oraclejdk12
  - openjdk12
services:
  - postgresql
before_script:
  - psql -c "CREATE USER testuser WITH PASSWORD 'password';" -U postgres
  - psql -c "CREATE DATABASE test;" -U postgres
deploy:
  provider: releases
  api_key: $GITHUB-TOKEN
  file: webapp-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    branch: travis_test