version: '3.1'


networks:
  webapp-db:
    driver: bridge

volumes:
  db-postg:

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webapp_data
    volumes:
      - db-postg:/var/lib/postgresql
    networks:
      - webapp-db

  webapp:
    image: webapp
    restart: always
    ports:
      - 8080:8080
    networks:
      - webapp-db
    depends_on:
      - db